DCEveryDayCase:
  case_settings:
    case_name: DCEveryDayCase
    keys_amount: 1
    claim_cooldown: 86400
    new_player_choice: case
    turn_off_daily_case_logic: false
  debug: false
  Languages: en_US
config:
  version: 1
  type: CONFIG