claim_cooldown: 86400  # 24 часа в секундах

placeholder:
  available: "Доступен ежедневный кейс: нажмите для получения"
  remaining: "До получения осталось: $d дн, $h ч, $m мин, $s сек"

case_name: "DCEveryDayCase" # название кейса на который будут выдаваться ключи и на который будет идти проверка ключей
keys_amout: "1" # сколько ключей за рас после окончания отсчета выдастся

debug: false # false or true, будет логировать в консоль только то когда игрокам выдается ключ