DCEveryDayCase:
  version: 2
  case_settings:
    case_name: DCEveryDayCase
    keys_amount: 1
    claim_cooldown: 86400
    new_player_choice: case
    turn_off_daily_case_logic: true
  debug: false
  placeholder:
    available: '&7Daily case is available: &aclick to receive'
    remaining: '&7Time remaining: &6$d days, &6$h hours, &6$m minutes, &6$s seconds'
  messages:
    log_console_give_key: 'Issued {key} key to player {player} for case {case}'
    info_placeholder: 'Information available only for players'
    case_granted_on: '&aNotifications enabled'
    case_granted_off: '&cNotifications disabled'
    only_for_players: 'This command is for players only.'
    no_permission: '&cYou don''t have permission.'
    case_ready: '&aYour daily case is ready!'
