claim_cooldown: 86400  # 24 hours in seconds

placeholder:
  available: "&7Daily case is available: &aclick to receive"
  remaining: "&7It remains before receiving: &6$d &7day, &6$h &7hour, &6$m &7min, &6$s &7sec"

case_name: "DCEveryDayCase" # the name of the case on which the key will be issued and the key check will be checked
keys_amount: "1" # how many keys per races after the end of the reference will be far out

debug: false # false or true, will log into the console only when the players are given the key

messages:
  log_console_give_key: "Issued {Key} The key (to her) to the player {Player} for the case {CASE}"
  info_placeholder: "Information is available only for players"