claim_cooldown: 86400  # 24 часа в секундах

placeholder:
  available: "Доступен ежедневный кейс: нажмите для получения"
  remaining: "До получения осталось: $d дн, $h ч, $m мин, $s сек"

case_name: "DCEveryDayCase" # название кейса на который будет выдаваться ключ и на который будет идти проверка ключей
keys_amount: "1" # сколько ключей за рас после окончания отсчета выдастся

debug: false # false or true, будет логировать в консоль только то когда игрокам выдается ключ

messages:
  log_console_give_key: "Выдано {key} ключ(ей) игроку {player} для кейса {case}"
  info_placeholder: "Информация доступна только для игроков"